[tool.poetry]
name = "oblig-2"
version = "0.1.0"
description = ""
authors = ["havardliebe <104149882+havardliebe@users.noreply.github.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
